const fs = require('fs');

const file = 'server/storage.ts';
let content = fs.readFileSync(file, 'utf8');

content = content.replace("  InsertInventarioMarketing,\n  TareaMarketing,\n  InsertTareaMarketing,\n  SegmentSupervisor,\n  InsertSegmentSupervisor,", "  InsertInventarioMarketing,\n  TareaMarketing,\n  InsertTareaMarketing,\n  CreatividadMarketing,\n  InsertCreatividadMarketing,\n  SegmentSupervisor,\n  InsertSegmentSupervisor,");
content = content.replace("  inventarioMarketing,\n  tareasMarketing,\n  segmentSupervisors,", "  inventarioMarketing,\n  tareasMarketing,\n  creatividadesMarketing,\n  segmentSupervisors,");

content = content.replace("  getTareaMarketingById(id: string): Promise<TareaMarketing | undefined>;\n  createTareaMarketing(data: InsertTareaMarketing): Promise<TareaMarketing>;\n  updateTareaMarketing(id: string, updates: Partial<InsertTareaMarketing>): Promise<TareaMarketing>;\n  deleteTareaMarketing(id: string): Promise<void>;\n\n  // ==================== GESTIÓN DE FONDOS ====================", "  getTareaMarketingById(id: string): Promise<TareaMarketing | undefined>;\n  createTareaMarketing(data: InsertTareaMarketing): Promise<TareaMarketing>;\n  updateTareaMarketing(id: string, updates: Partial<InsertTareaMarketing>): Promise<TareaMarketing>;\n  deleteTareaMarketing(id: string): Promise<void>;\n\n  // Creatividades Marketing\n  getCreatividadesMarketing(filters?: { mes?: number; anio?: number; estado?: string; tipo?: string; plataforma?: string }): Promise<CreatividadMarketing[]>;\n  getCreatividadMarketingById(id: string): Promise<CreatividadMarketing | undefined>;\n  createCreatividadMarketing(data: InsertCreatividadMarketing): Promise<CreatividadMarketing>;\n  updateCreatividadMarketing(id: string, updates: Partial<InsertCreatividadMarketing>): Promise<CreatividadMarketing>;\n  deleteCreatividadMarketing(id: string): Promise<void>;\n\n  // ==================== GESTIÓN DE FONDOS ====================");

content = content.replace("  async deleteTareaMarketing(id: string): Promise<void> {\n    await db\n      .delete(tareasMarketing)\n      .where(eq(tareasMarketing.id, id));\n  }\n\n  // ==================== GESTIÓN DE FONDOS ====================", "  async deleteTareaMarketing(id: string): Promise<void> {\n    await db\n      .delete(tareasMarketing)\n      .where(eq(tareasMarketing.id, id));\n  }\n\n  // ==================== CREATIVIDADES MARKETING ====================\n\n  async getCreatividadesMarketing(filters?: { mes?: number; anio?: number; estado?: string; tipo?: string; plataforma?: string }): Promise<CreatividadMarketing[]> {\n    const conditions = [];\n\n    if (filters?.mes) {\n      conditions.push(eq(creatividadesMarketing.mes, filters.mes));\n    }\n    if (filters?.anio) {\n      conditions.push(eq(creatividadesMarketing.anio, filters.anio));\n    }\n    if (filters?.estado) {\n      conditions.push(eq(creatividadesMarketing.estado, filters.estado));\n    }\n    if (filters?.tipo) {\n      conditions.push(eq(creatividadesMarketing.tipo, filters.tipo));\n    }\n    if (filters?.plataforma) {\n      conditions.push(eq(creatividadesMarketing.plataforma, filters.plataforma));\n    }\n\n    return await db\n      .select()\n      .from(creatividadesMarketing)\n      .where(conditions.length > 0 ? and(...conditions) : undefined)\n      .orderBy(desc(creatividadesMarketing.createdAt));\n  }\n\n  async getCreatividadMarketingById(id: string): Promise<CreatividadMarketing | undefined> {\n    const [result] = await db\n      .select()\n      .from(creatividadesMarketing)\n      .where(eq(creatividadesMarketing.id, id));\n    return result;\n  }\n\n  async createCreatividadMarketing(data: InsertCreatividadMarketing): Promise<CreatividadMarketing> {\n    const [result] = await db\n      .insert(creatividadesMarketing)\n      .values(data)\n      .returning();\n    return result;\n  }\n\n  async updateCreatividadMarketing(id: string, updates: Partial<InsertCreatividadMarketing>): Promise<CreatividadMarketing> {\n    const updateData: any = {\n      ...updates,\n      updatedAt: new Date(),\n    };\n\n    const [result] = await db\n      .update(creatividadesMarketing)\n      .set(updateData)\n      .where(eq(creatividadesMarketing.id, id))\n      .returning();\n    return result;\n  }\n\n  async deleteCreatividadMarketing(id: string): Promise<void> {\n    await db\n      .delete(creatividadesMarketing)\n      .where(eq(creatividadesMarketing.id, id));\n  }\n\n  // ==================== GESTIÓN DE FONDOS ====================");

fs.writeFileSync(file, content);
console.log('Done modifying storage');
