CREATE SCHEMA "ventas";
--> statement-breakpoint
CREATE TABLE "bases" (
	"id" integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "bases_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START WITH 1 CACHE 1),
	"base_id" text NOT NULL,
	"tipo_base" text NOT NULL,
	"color_base" text NOT NULL,
	"costo_kg_clp" numeric(15, 2) NOT NULL,
	"notas" text,
	"created_at" timestamp DEFAULT now(),
	"updated_at" timestamp DEFAULT now(),
	CONSTRAINT "bases_base_id_unique" UNIQUE("base_id")
);
--> statement-breakpoint
CREATE TABLE "clients" (
	"id" varchar PRIMARY KEY DEFAULT gen_random_uuid() NOT NULL,
	"created_at" timestamp DEFAULT now(),
	"updated_at" timestamp DEFAULT now(),
	"idmaeen" numeric(15, 5),
	"koen" varchar,
	"nokoen" text NOT NULL,
	"rten" varchar,
	"tien" varchar,
	"suen" varchar,
	"tiposuc" varchar,
	"sien" text,
	"gien" text,
	"paen" varchar,
	"cien" varchar,
	"cmen" varchar,
	"dien" text,
	"zoen" varchar,
	"comuna" varchar,
	"provincia" varchar,
	"departame" varchar,
	"distrito" varchar,
	"codubigeo" varchar,
	"urbaniz" varchar,
	"cpostal" varchar,
	"foen" varchar,
	"faen" varchar,
	"email" text,
	"emailcomer" text,
	"cnen" varchar,
	"cnen2" varchar,
	"crsd" numeric(15, 2),
	"crch" numeric(15, 2),
	"crlt" numeric(15, 2),
	"crpa" numeric(15, 2),
	"crto" numeric(15, 2),
	"cren" numeric(15, 2),
	"fevecren" varchar,
	"feultr" varchar,
	"nuvecr" numeric(15, 2),
	"dccr" numeric(15, 2),
	"incr" numeric(15, 2),
	"popicr" numeric(15, 2),
	"koplcr" varchar,
	"kofuen" varchar,
	"assigned_salesperson_user_id" varchar,
	"user_id" varchar,
	"lcen" varchar,
	"lven" varchar,
	"prefen" varchar,
	"porprefen" numeric(15, 2),
	"contab" varchar,
	"subauxi" varchar,
	"contabvta" varchar,
	"subauxivta" varchar,
	"codcc" varchar,
	"nutransmi" varchar,
	"ruen" varchar,
	"cpen" numeric(15, 2),
	"cobrador" varchar,
	"diacobra" numeric(15, 2),
	"rutalun" integer,
	"rutamar" integer,
	"rutamie" integer,
	"rutajue" integer,
	"rutavie" integer,
	"rutasab" integer,
	"rutadom" integer,
	"bloqueado" integer,
	"actien" integer,
	"habilita" varchar,
	"bloqencom" integer,
	"blovenex" integer,
	"dimoper" numeric(15, 2),
	"tipoen" varchar,
	"tamaen" varchar,
	"claveen" varchar,
	"acteco" varchar,
	"cattrib" varchar,
	"agretiva" integer,
	"agretiibb" integer,
	"agretgan" integer,
	"agperiva" integer,
	"agperiibb" integer,
	"catlegret" varchar,
	"catlegmer" varchar,
	"imptoret" numeric(15, 2),
	"tiporuc" varchar,
	"podetrac" integer,
	"proteacum" numeric(15, 2),
	"protevige" numeric(15, 2),
	"diasvenci" numeric(15, 2),
	"nvvpidepie" integer,
	"recepelect" integer,
	"nvvobli" integer,
	"occobli" integer,
	"extenxml" varchar,
	"codconve" varchar,
	"notraedeud" varchar,
	"nokoenamp" text,
	"transpoen" varchar,
	"oben" text,
	"diprve" numeric(15, 2),
	"valivenpag" numeric(15, 2),
	"tipocontr" varchar,
	"ferefauto" varchar,
	"cuentabco" varchar,
	"koendpen" varchar,
	"suendpen" varchar,
	"koenal" varchar,
	"kofuweb" varchar,
	"secuecom" integer,
	"secueven" integer,
	"avisadpven" integer,
	"entiliga" varchar,
	"porceliga" numeric(15, 2),
	"gpslat" numeric(15, 8),
	"gpslon" numeric(15, 8),
	"fecreen" varchar,
	"femoen" varchar,
	"feemdo" varchar,
	"firma" varchar,
	"nodocum" varchar,
	"moctaen" varchar,
	"ctasdelaen" varchar,
	"nacionen" varchar,
	"dirparen" text,
	"fecnacen" varchar,
	"estciven" varchar,
	"profecen" varchar,
	"conyugen" varchar,
	"rutconen" varchar,
	"rutsocen" varchar,
	"sexoen" varchar,
	"relacien" varchar,
	"anexen1" varchar,
	"anexen2" varchar,
	"anexen3" varchar,
	"anexen4" varchar,
	"dten" varchar,
	"uren" varchar,
	"actecobco" varchar,
	"deudaven" numeric(15, 2),
	"chvnocan" numeric(15, 2),
	"ltvnocan" numeric(15, 2),
	"pagnocan" numeric(15, 2),
	"anticipos" numeric(15, 2),
	CONSTRAINT "clients_koen_unique" UNIQUE("koen")
);
--> statement-breakpoint
CREATE TABLE "colores" (
	"id" integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "colores_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START WITH 1 CACHE 1),
	"color_id" text NOT NULL,
	"nombre_color" text NOT NULL,
	"base_id" text NOT NULL,
	"observaciones" text,
	"notas" text,
	"created_at" timestamp DEFAULT now(),
	"updated_at" timestamp DEFAULT now(),
	CONSTRAINT "colores_color_id_unique" UNIQUE("color_id")
);
--> statement-breakpoint
CREATE TABLE "comuna_region_mapping" (
	"id" varchar PRIMARY KEY DEFAULT gen_random_uuid() NOT NULL,
	"comuna" varchar NOT NULL,
	"region" varchar NOT NULL,
	"comuna_normalized" varchar NOT NULL,
	"region_normalized" varchar NOT NULL,
	"is_active" boolean DEFAULT true,
	"matching_strategy" varchar DEFAULT 'exact',
	"created_at" timestamp DEFAULT now(),
	"updated_at" timestamp DEFAULT now(),
	CONSTRAINT "unique_comuna_region" UNIQUE("comuna_normalized")
);
--> statement-breakpoint
CREATE TABLE "contactos_visita" (
	"id" varchar PRIMARY KEY DEFAULT gen_random_uuid() NOT NULL,
	"visita_id" varchar NOT NULL,
	"contratista_nombre" varchar,
	"contratista_telefono" varchar,
	"contratista_email" varchar,
	"administrador_nombre" varchar,
	"administrador_telefono" varchar,
	"administrador_email" varchar,
	"supervisor_nombre" varchar,
	"supervisor_telefono" varchar,
	"supervisor_email" varchar,
	"contacto_general" text,
	"created_at" timestamp DEFAULT now(),
	"updated_at" timestamp DEFAULT now()
);
--> statement-breakpoint
CREATE TABLE "ecommerce_categories" (
	"id" varchar PRIMARY KEY DEFAULT gen_random_uuid() NOT NULL,
	"nombre" varchar NOT NULL,
	"descripcion" text,
	"activa" boolean DEFAULT true,
	"created_at" timestamp DEFAULT now(),
	"updated_at" timestamp DEFAULT now(),
	CONSTRAINT "ecommerce_categories_nombre_unique" UNIQUE("nombre")
);
--> statement-breakpoint
CREATE TABLE "ecommerce_orders" (
	"id" varchar PRIMARY KEY DEFAULT gen_random_uuid() NOT NULL,
	"client_id" varchar NOT NULL,
	"client_name" text NOT NULL,
	"client_email" varchar,
	"client_phone" varchar,
	"assigned_salesperson_id" varchar,
	"assigned_salesperson_name" varchar,
	"assigned_supervisor_id" varchar,
	"items" jsonb NOT NULL,
	"subtotal" numeric(15, 2) NOT NULL,
	"tax" numeric(15, 2) NOT NULL,
	"total" numeric(15, 2) NOT NULL,
	"status" varchar DEFAULT 'pending',
	"notes" text,
	"shipping_address" text,
	"approved_at" timestamp,
	"approved_by_id" varchar,
	"modified_at" timestamp,
	"modified_by_id" varchar,
	"quote_id" varchar,
	"created_at" timestamp DEFAULT now(),
	"updated_at" timestamp DEFAULT now()
);
--> statement-breakpoint
CREATE TABLE "ecommerce_product_groups" (
	"id" varchar PRIMARY KEY DEFAULT gen_random_uuid() NOT NULL,
	"nombre" varchar NOT NULL,
	"descripcion" text,
	"imagen_principal" varchar,
	"categoria" varchar,
	"activo" boolean DEFAULT true,
	"orden" integer DEFAULT 0,
	"created_at" timestamp DEFAULT now(),
	"updated_at" timestamp DEFAULT now()
);
--> statement-breakpoint
CREATE TABLE "ecommerce_products" (
	"id" varchar PRIMARY KEY DEFAULT gen_random_uuid() NOT NULL,
	"price_list_id" varchar NOT NULL,
	"group_id" varchar,
	"activo" boolean DEFAULT false,
	"categoria" varchar,
	"descripcion" text,
	"imagen_url" varchar,
	"precio_ecommerce" numeric(15, 2),
	"variant_label" varchar,
	"is_main_variant" boolean DEFAULT false,
	"orden" integer DEFAULT 0,
	"created_at" timestamp DEFAULT now(),
	"updated_at" timestamp DEFAULT now(),
	CONSTRAINT "unique_price_list_product" UNIQUE("price_list_id")
);
--> statement-breakpoint
CREATE TABLE "envases" (
	"id" integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "envases_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START WITH 1 CACHE 1),
	"envase_id" text NOT NULL,
	"material" text NOT NULL,
	"capacidad" text NOT NULL,
	"kg_por_envase" numeric(10, 3) NOT NULL,
	"costo_envase_clp" numeric(15, 2) NOT NULL,
	"notas" text,
	"created_at" timestamp DEFAULT now(),
	"updated_at" timestamp DEFAULT now(),
	CONSTRAINT "envases_envase_id_unique" UNIQUE("envase_id")
);
--> statement-breakpoint
CREATE TABLE "ventas"."etl_execution_log" (
	"id" varchar PRIMARY KEY DEFAULT gen_random_uuid() NOT NULL,
	"execution_date" timestamp DEFAULT now() NOT NULL,
	"status" varchar(20) NOT NULL,
	"period" varchar(7) NOT NULL,
	"document_types" text NOT NULL,
	"branches" text NOT NULL,
	"records_processed" integer,
	"execution_time_ms" integer,
	"error_message" text,
	"statistics" text,
	"watermark_date" timestamp
);
--> statement-breakpoint
CREATE TABLE "evaluaciones_tecnicas" (
	"id" varchar PRIMARY KEY DEFAULT gen_random_uuid() NOT NULL,
	"producto_evaluado_id" varchar NOT NULL,
	"aplicacion" varchar,
	"tipo_superficie" text,
	"ambiente" varchar,
	"condiciones_climaticas" text,
	"dilucion" text,
	"observaciones_tecnicas" text,
	"preparacion_superficie" text,
	"rendimiento" text,
	"adherencia" text,
	"anomalias" text,
	"acciones_recomendadas" text,
	"imagenes_urls" jsonb DEFAULT '[]'::jsonb,
	"created_at" timestamp DEFAULT now(),
	"updated_at" timestamp DEFAULT now()
);
--> statement-breakpoint
CREATE TABLE "evidencias" (
	"id" varchar PRIMARY KEY DEFAULT gen_random_uuid() NOT NULL,
	"visita_id" varchar,
	"producto_evaluado_id" varchar,
	"reclamo_id" varchar,
	"tipo_evidencia" varchar NOT NULL,
	"nombre_archivo" varchar NOT NULL,
	"url_archivo" text NOT NULL,
	"tipo_archivo" varchar,
	"tamanio" integer,
	"descripcion" text,
	"created_at" timestamp DEFAULT now()
);
--> statement-breakpoint
CREATE TABLE "ventas"."fact_ventas" (
	"idmaeddo" numeric(20, 0) PRIMARY KEY NOT NULL,
	"idmaeedo" numeric(20, 0),
	"tido" text,
	"nudo" numeric(20, 0),
	"endo" text,
	"suendo" text,
	"sudo" numeric(20, 0),
	"feemdo" date,
	"feulvedo" date,
	"esdo" text,
	"espgdo" text,
	"kofudo" text,
	"modo" text,
	"timodo" text,
	"tamodo" numeric(18, 6),
	"caprad" numeric(20, 0),
	"caprex" numeric(20, 0),
	"vanedo" numeric(20, 0),
	"vaivdo" numeric(18, 6),
	"vabrdo" numeric(20, 0),
	"lilg" text,
	"nulido" numeric(20, 0),
	"sulido" numeric(20, 0),
	"luvtlido" numeric(18, 6),
	"bosulido" numeric(20, 0),
	"kofulido" text,
	"prct" boolean,
	"tict" numeric(18, 6),
	"tipr" text,
	"nusepr" numeric(18, 6),
	"koprct" text,
	"udtrpr" numeric(20, 0),
	"rludpr" numeric(18, 6),
	"caprco1" numeric(18, 6),
	"caprad1" numeric(18, 6),
	"caprex1" numeric(18, 6),
	"caprnc1" numeric(18, 6),
	"ud01pr" text,
	"caprco2" numeric(20, 0),
	"caprad2" numeric(20, 0),
	"caprex2" numeric(20, 0),
	"caprnc2" numeric(20, 0),
	"ud02pr" text,
	"ppprne" numeric(18, 6),
	"ppprbr" numeric(18, 6),
	"vaneli" numeric(20, 0),
	"vabrli" numeric(20, 0),
	"feemli" date,
	"feerli" timestamp,
	"ppprpm" numeric(18, 6),
	"ppprpmifrs" numeric(18, 6),
	"logistica" numeric(20, 0),
	"eslido" text,
	"ppprnere1" numeric(18, 6),
	"ppprnere2" numeric(18, 6),
	"fmpr" numeric(20, 0),
	"mrpr" numeric(18, 6),
	"zona" numeric(18, 6),
	"ruen" numeric(18, 6),
	"recaprre" boolean,
	"pfpr" numeric(18, 6),
	"hfpr" numeric(18, 6),
	"monto" numeric(20, 2),
	"ocdo" text,
	"nokoprct" text,
	"nokozo" numeric(18, 6),
	"nosudo" text,
	"nokofu" text,
	"nokofudo" text,
	"nobosuli" text,
	"nokoen" text,
	"noruen" text,
	"nomrpr" numeric(18, 6),
	"nofmpr" text,
	"nopfpr" text,
	"nohfpr" text,
	"devol1" numeric(20, 0),
	"devol2" numeric(20, 0),
	"stockfis" numeric(20, 0),
	"listacost" numeric(18, 6),
	"liscosmod" numeric(20, 0)
);
--> statement-breakpoint
CREATE TABLE "file_uploads" (
	"id" varchar PRIMARY KEY DEFAULT gen_random_uuid() NOT NULL,
	"file_type" varchar NOT NULL,
	"file_name" varchar NOT NULL,
	"uploaded_by" varchar NOT NULL,
	"uploaded_at" timestamp DEFAULT now(),
	"records_imported" integer DEFAULT 0,
	"records_errors" integer DEFAULT 0,
	"status" varchar DEFAULT 'pending',
	"error_message" text,
	"file_size" integer,
	"total_files" integer DEFAULT 0,
	"processed_files" integer DEFAULT 0,
	"successful_files" integer DEFAULT 0,
	"failed_files" integer DEFAULT 0,
	"progress_data" jsonb,
	"result_data" jsonb,
	"is_completed" boolean DEFAULT false,
	"completed_at" timestamp,
	"created_at" timestamp DEFAULT now()
);
--> statement-breakpoint
CREATE TABLE "firmas_digitales" (
	"id" varchar PRIMARY KEY DEFAULT gen_random_uuid() NOT NULL,
	"visita_id" varchar NOT NULL,
	"tipo_firma" varchar NOT NULL,
	"nombre_firmante" varchar,
	"cargo_firmante" varchar,
	"datos_base64" text NOT NULL,
	"created_at" timestamp DEFAULT now()
);
--> statement-breakpoint
CREATE TABLE "gastos_empresariales" (
	"id" varchar PRIMARY KEY DEFAULT gen_random_uuid() NOT NULL,
	"monto" numeric(15, 2) NOT NULL,
	"descripcion" text NOT NULL,
	"user_id" varchar NOT NULL,
	"centro_costos" varchar(255),
	"categoria" varchar(100) NOT NULL,
	"tipo_gasto" varchar(100) DEFAULT 'Reembolso' NOT NULL,
	"tipo_documento" varchar(100),
	"proveedor" varchar(255),
	"rut_proveedor" varchar(20),
	"numero_documento" varchar(100),
	"fecha_emision" date,
	"archivo_url" varchar(500),
	"estado" varchar(50) DEFAULT 'pendiente' NOT NULL,
	"supervisor_id" varchar,
	"fecha_aprobacion" timestamp,
	"comentario_rechazo" text,
	"created_at" timestamp DEFAULT now(),
	"updated_at" timestamp DEFAULT now()
);
--> statement-breakpoint
CREATE TABLE "goals" (
	"id" varchar PRIMARY KEY DEFAULT gen_random_uuid() NOT NULL,
	"type" varchar NOT NULL,
	"target" varchar,
	"amount" numeric(15, 2) NOT NULL,
	"period" varchar NOT NULL,
	"description" text,
	"created_at" timestamp DEFAULT now(),
	"updated_at" timestamp DEFAULT now()
);
--> statement-breakpoint
CREATE TABLE "inventario_marketing" (
	"id" varchar PRIMARY KEY DEFAULT gen_random_uuid() NOT NULL,
	"nombre" varchar(255) NOT NULL,
	"descripcion" text,
	"cantidad" integer DEFAULT 0 NOT NULL,
	"unidad" varchar(50) DEFAULT 'unidades' NOT NULL,
	"ubicacion" varchar(255),
	"costo_unitario" numeric(15, 2),
	"proveedor" varchar(255),
	"estado" varchar DEFAULT 'disponible' NOT NULL,
	"stock_minimo" integer DEFAULT 0,
	"created_at" timestamp DEFAULT now(),
	"updated_at" timestamp DEFAULT now()
);
--> statement-breakpoint
CREATE TABLE "notifications" (
	"id" varchar PRIMARY KEY DEFAULT gen_random_uuid() NOT NULL,
	"user_id" varchar NOT NULL,
	"type" varchar NOT NULL,
	"title" varchar NOT NULL,
	"message" text NOT NULL,
	"related_order_id" varchar,
	"related_quote_id" varchar,
	"related_task_id" varchar,
	"read" boolean DEFAULT false,
	"read_at" timestamp,
	"action_url" varchar,
	"created_at" timestamp DEFAULT now()
);
--> statement-breakpoint
CREATE TABLE "nvv_pending_sales" (
	"id" varchar PRIMARY KEY DEFAULT gen_random_uuid() NOT NULL,
	"IDMAEEDO" numeric(15, 2),
	"TIDO" varchar,
	"NUDO" varchar,
	"ENDO" varchar,
	"SUENDO" varchar,
	"SUDO" varchar,
	"FEEMDO" date,
	"FEER" date,
	"MODO" varchar,
	"TIMODO" varchar,
	"TIDEVE" varchar,
	"TIDEVEFE" date,
	"TIDEVEHO" varchar,
	"PPPRNE" numeric(15, 2),
	"TAMOPPPR" numeric(15, 2),
	"VANELI" numeric(15, 2),
	"FEEMLI" date,
	"KOFULIDO" varchar,
	"LILG" varchar,
	"PRCT" varchar,
	"NULIDO" varchar,
	"FEERLI" date,
	"SULIDO" varchar,
	"BOSULIDO" varchar,
	"LUVTLIDO" integer,
	"KOPRCT" varchar,
	"UD01PR" varchar,
	"NOKOZO" varchar,
	"IDMAEDDO" numeric(15, 2),
	"NUSEPR" varchar,
	"CAPRCO1" numeric(10, 2),
	"CAPRAD1" numeric(10, 2),
	"CAPREX1" numeric(10, 2),
	"UD02PR" varchar,
	"CAPRCO2" numeric(10, 2),
	"CAPRAD2" numeric(10, 2),
	"CAPREX2" numeric(10, 2),
	"OCDO" varchar,
	"OBDO" varchar,
	"NOKOEN" varchar,
	"ZOEN" varchar,
	"DIEN" varchar,
	"COMUNA" varchar,
	"TIPR" varchar,
	"NOKOPR" text,
	"PFPR" varchar,
	"FMPR" varchar,
	"RUPR" varchar,
	"MRPR" varchar,
	"STFI1" numeric(10, 2),
	"STFI2" numeric(10, 2),
	"PRRG" varchar,
	"KOPRTE" varchar,
	"ENDOFI" varchar,
	"UBICACION" varchar,
	"OBSERVA" text,
	"cantidad_pendiente" numeric(10, 2),
	"total_pendiente" numeric(15, 2),
	"imported_at" timestamp DEFAULT now(),
	"import_batch" varchar,
	"created_at" timestamp DEFAULT now(),
	"updated_at" timestamp DEFAULT now()
);
--> statement-breakpoint
CREATE TABLE "obras" (
	"id" varchar PRIMARY KEY DEFAULT gen_random_uuid() NOT NULL,
	"cliente_id" varchar NOT NULL,
	"nombre" text NOT NULL,
	"direccion" text NOT NULL,
	"descripcion" text,
	"estado" varchar DEFAULT 'activa' NOT NULL,
	"fecha_inicio" date,
	"fecha_estimada_fin" date,
	"created_at" timestamp DEFAULT now(),
	"updated_at" timestamp DEFAULT now()
);
--> statement-breakpoint
CREATE TABLE "order_items" (
	"id" varchar PRIMARY KEY DEFAULT gen_random_uuid() NOT NULL,
	"order_id" varchar NOT NULL,
	"type" varchar DEFAULT 'standard' NOT NULL,
	"product_code" varchar,
	"product_name" text NOT NULL,
	"custom_sku" varchar,
	"cost_of_production" numeric(15, 2),
	"profit_margin" numeric(5, 2),
	"pricing_mode" varchar,
	"quantity" numeric(10, 2) NOT NULL,
	"unit_price" numeric(15, 2) NOT NULL,
	"total_price" numeric(15, 2) NOT NULL,
	"notes" text,
	"created_at" timestamp DEFAULT now()
);
--> statement-breakpoint
CREATE TABLE "orders" (
	"id" varchar PRIMARY KEY DEFAULT gen_random_uuid() NOT NULL,
	"order_number" varchar NOT NULL,
	"client_name" text NOT NULL,
	"client_id" varchar,
	"client_rut" varchar,
	"client_email" varchar,
	"client_phone" varchar,
	"client_address" text,
	"created_by" varchar NOT NULL,
	"status" varchar DEFAULT 'draft',
	"priority" varchar DEFAULT 'medium',
	"notes" text,
	"estimated_delivery_date" timestamp,
	"subtotal" numeric(15, 2),
	"discount" numeric(15, 2) DEFAULT '0',
	"tax_rate" numeric(5, 2) DEFAULT '19',
	"tax_amount" numeric(15, 2),
	"total" numeric(15, 2),
	"total_amount" numeric(15, 2),
	"created_at" timestamp DEFAULT now(),
	"updated_at" timestamp DEFAULT now(),
	CONSTRAINT "orders_order_number_unique" UNIQUE("order_number")
);
--> statement-breakpoint
CREATE TABLE "parametros" (
	"id" integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "parametros_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START WITH 1 CACHE 1),
	"parametro" text NOT NULL,
	"valor" numeric(15, 6) NOT NULL,
	"created_at" timestamp DEFAULT now(),
	"updated_at" timestamp DEFAULT now(),
	CONSTRAINT "parametros_parametro_unique" UNIQUE("parametro")
);
--> statement-breakpoint
CREATE TABLE "pigments" (
	"id" integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "pigments_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START WITH 1 CACHE 1),
	"pigmento_code" text NOT NULL,
	"nombre" text NOT NULL,
	"compatible_base" text NOT NULL,
	"costo_kg_clp" numeric(15, 2) NOT NULL,
	"proveedor" text,
	"notas" text,
	"created_at" timestamp DEFAULT now(),
	"updated_at" timestamp DEFAULT now(),
	CONSTRAINT "pigments_pigmento_code_unique" UNIQUE("pigmento_code")
);
--> statement-breakpoint
CREATE TABLE "presupuesto_marketing" (
	"id" varchar PRIMARY KEY DEFAULT gen_random_uuid() NOT NULL,
	"mes" integer NOT NULL,
	"anio" integer NOT NULL,
	"presupuesto_total" numeric(15, 2) NOT NULL,
	"created_at" timestamp DEFAULT now(),
	"updated_at" timestamp DEFAULT now()
);
--> statement-breakpoint
CREATE TABLE "price_list" (
	"id" varchar PRIMARY KEY DEFAULT gen_random_uuid() NOT NULL,
	"codigo" varchar NOT NULL,
	"producto" text NOT NULL,
	"unidad" varchar,
	"lista" numeric(15, 2),
	"desc10" numeric(15, 2),
	"desc10_5" numeric(15, 2),
	"desc10_5_3" numeric(15, 2),
	"minimo" numeric(15, 2),
	"canal_digital" numeric(15, 2),
	"es_personalizado" varchar DEFAULT 'No',
	"costo_produccion" numeric(15, 2),
	"porcentaje_utilidad" numeric(10, 2),
	"modo_precio" varchar,
	"created_at" timestamp DEFAULT now(),
	"updated_at" timestamp DEFAULT now(),
	CONSTRAINT "price_list_codigo_unique" UNIQUE("codigo")
);
--> statement-breakpoint
CREATE TABLE "product_images" (
	"id" varchar PRIMARY KEY DEFAULT gen_random_uuid() NOT NULL,
	"ecommerce_product_id" varchar NOT NULL,
	"image_url" varchar NOT NULL,
	"alt_text" varchar,
	"orden" integer DEFAULT 0,
	"tipo_imagen" varchar DEFAULT 'producto',
	"activa" boolean DEFAULT true,
	"created_at" timestamp DEFAULT now(),
	"updated_at" timestamp DEFAULT now()
);
--> statement-breakpoint
CREATE TABLE "product_price_history" (
	"id" varchar PRIMARY KEY DEFAULT gen_random_uuid() NOT NULL,
	"product_sku" varchar NOT NULL,
	"old_price" numeric(15, 2),
	"new_price" numeric(15, 2) NOT NULL,
	"changed_by" varchar,
	"change_reason" text,
	"effective_date" timestamp DEFAULT now(),
	"created_at" timestamp DEFAULT now()
);
--> statement-breakpoint
CREATE TABLE "product_stock" (
	"id" varchar PRIMARY KEY DEFAULT gen_random_uuid() NOT NULL,
	"kopr" varchar NOT NULL,
	"product_sku" varchar NOT NULL,
	"kosu" varchar NOT NULL,
	"kobo" varchar NOT NULL,
	"datosubic" text,
	"branch_code" varchar NOT NULL,
	"warehouse_code" varchar NOT NULL,
	"warehouse_location" text,
	"physical_stock1" numeric(15, 4),
	"physical_stock2" numeric(15, 4),
	"available_stock1" numeric(15, 4),
	"available_stock2" numeric(15, 4),
	"committed_stock1" numeric(15, 4),
	"committed_stock2" numeric(15, 4),
	"committed_stock1_alt" numeric(15, 4),
	"committed_stock2_alt" numeric(15, 4),
	"committed_stock_alt1" numeric(15, 4),
	"committed_stock_alt2" numeric(15, 4),
	"receipt_no_invoice1" numeric(15, 4),
	"receipt_no_invoice2" numeric(15, 4),
	"dispatch_no_invoice1" numeric(15, 4),
	"dispatch_no_invoice2" numeric(15, 4),
	"fmpr" varchar,
	"pfpr" varchar,
	"hfpr" varchar,
	"rupr" varchar,
	"mrpr" varchar,
	"rlud" numeric(10, 2),
	"last_updated" timestamp DEFAULT now(),
	"created_at" timestamp DEFAULT now(),
	CONSTRAINT "unique_product_stock_location" UNIQUE("kopr","kosu","kobo"),
	CONSTRAINT "unique_product_stock_location_compat" UNIQUE("product_sku","branch_code","warehouse_code")
);
--> statement-breakpoint
CREATE TABLE "productos_evaluados" (
	"id" varchar PRIMARY KEY DEFAULT gen_random_uuid() NOT NULL,
	"visita_id" varchar NOT NULL,
	"producto_id" varchar,
	"producto_manual" text,
	"formato" varchar,
	"color" varchar,
	"lote" varchar,
	"fecha_llegada" date,
	"metros_cuadrados_aplicados" numeric(10, 2),
	"porcentaje_avance" numeric(5, 2),
	"created_at" timestamp DEFAULT now(),
	"updated_at" timestamp DEFAULT now()
);
--> statement-breakpoint
CREATE TABLE "products" (
	"id" varchar PRIMARY KEY DEFAULT gen_random_uuid() NOT NULL,
	"kopr" varchar NOT NULL,
	"name" text NOT NULL,
	"ud02pr" varchar,
	"price_product" numeric(15, 2),
	"price_offer" numeric(15, 2),
	"show_in_store" boolean DEFAULT false,
	"slug" varchar,
	"ecom_active" boolean DEFAULT false,
	"ecom_price" numeric(15, 2),
	"category" varchar,
	"tags" text[],
	"images" jsonb DEFAULT '[]'::jsonb,
	"seo_title" varchar,
	"seo_description" text,
	"og_image_url" varchar,
	"active" boolean DEFAULT true,
	"created_at" timestamp DEFAULT now(),
	"updated_at" timestamp DEFAULT now(),
	CONSTRAINT "products_kopr_unique" UNIQUE("kopr")
);
--> statement-breakpoint
CREATE TABLE "promesas_compra" (
	"id" varchar PRIMARY KEY DEFAULT gen_random_uuid() NOT NULL,
	"vendedor_id" varchar NOT NULL,
	"cliente_id" varchar NOT NULL,
	"cliente_nombre" varchar(255) NOT NULL,
	"monto_prometido" numeric(15, 2) NOT NULL,
	"semana" varchar(10) NOT NULL,
	"anio" integer NOT NULL,
	"numero_semana" integer NOT NULL,
	"fecha_inicio" date NOT NULL,
	"fecha_fin" date NOT NULL,
	"observaciones" text,
	"created_at" timestamp DEFAULT now(),
	"updated_at" timestamp DEFAULT now()
);
--> statement-breakpoint
CREATE TABLE "quote_items" (
	"id" varchar PRIMARY KEY DEFAULT gen_random_uuid() NOT NULL,
	"quote_id" varchar NOT NULL,
	"type" varchar NOT NULL,
	"product_code" varchar,
	"product_name" text NOT NULL,
	"custom_sku" varchar,
	"cost_of_production" numeric(15, 2),
	"profit_margin" numeric(5, 2),
	"pricing_mode" varchar,
	"quantity" numeric(10, 2) NOT NULL,
	"unit_price" numeric(15, 2) NOT NULL,
	"total_price" numeric(15, 2) NOT NULL,
	"notes" text,
	"created_at" timestamp DEFAULT now()
);
--> statement-breakpoint
CREATE TABLE "quotes" (
	"id" varchar PRIMARY KEY DEFAULT gen_random_uuid() NOT NULL,
	"quote_number" varchar NOT NULL,
	"client_name" text NOT NULL,
	"client_id" varchar,
	"client_rut" varchar,
	"client_email" varchar,
	"client_phone" varchar,
	"client_address" text,
	"created_by" varchar NOT NULL,
	"status" varchar DEFAULT 'draft',
	"valid_until" timestamp,
	"subtotal" numeric(15, 2),
	"discount" numeric(15, 2) DEFAULT '0',
	"tax_rate" numeric(5, 2) DEFAULT '19',
	"tax_amount" numeric(15, 2),
	"total" numeric(15, 2),
	"notes" text,
	"created_at" timestamp DEFAULT now(),
	"updated_at" timestamp DEFAULT now(),
	CONSTRAINT "quotes_quote_number_unique" UNIQUE("quote_number")
);
--> statement-breakpoint
CREATE TABLE "recetas" (
	"id" integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "recetas_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START WITH 1 CACHE 1),
	"color_id" text NOT NULL,
	"pigmento_code" text NOT NULL,
	"fraccion_peso" numeric(10, 6) NOT NULL,
	"created_at" timestamp DEFAULT now(),
	"updated_at" timestamp DEFAULT now()
);
--> statement-breakpoint
CREATE TABLE "reclamos" (
	"id" varchar PRIMARY KEY DEFAULT gen_random_uuid() NOT NULL,
	"visita_id" varchar NOT NULL,
	"descripcion" text NOT NULL,
	"lote_involucrado" varchar,
	"sector_afectado" text,
	"observacion_tecnica" text,
	"requiere_analisis_laboratorio" boolean DEFAULT false,
	"estado" varchar DEFAULT 'pendiente',
	"notas_resolucion" text,
	"created_at" timestamp DEFAULT now(),
	"updated_at" timestamp DEFAULT now()
);
--> statement-breakpoint
CREATE TABLE "reclamos_generales" (
	"id" varchar PRIMARY KEY DEFAULT gen_random_uuid() NOT NULL,
	"client_name" text NOT NULL,
	"client_rut" varchar,
	"client_email" varchar,
	"client_phone" varchar,
	"client_address" text,
	"product_name" text NOT NULL,
	"product_sku" varchar,
	"lote" varchar,
	"description" text NOT NULL,
	"gravedad" varchar NOT NULL,
	"estado" varchar DEFAULT 'registrado' NOT NULL,
	"vendedor_id" varchar NOT NULL,
	"vendedor_name" varchar,
	"tecnico_id" varchar,
	"tecnico_name" varchar,
	"derivado_laboratorio" boolean DEFAULT false,
	"derivado_produccion" boolean DEFAULT false,
	"informe_laboratorio" text,
	"informe_produccion" text,
	"informe_tecnico" text,
	"notas_internas" text,
	"fecha_registro" timestamp DEFAULT now(),
	"fecha_asignacion_tecnico" timestamp,
	"fecha_envio_laboratorio" timestamp,
	"fecha_respuesta_laboratorio" timestamp,
	"fecha_cierre" timestamp,
	"created_at" timestamp DEFAULT now(),
	"updated_at" timestamp DEFAULT now()
);
--> statement-breakpoint
CREATE TABLE "reclamos_generales_historial" (
	"id" varchar PRIMARY KEY DEFAULT gen_random_uuid() NOT NULL,
	"reclamo_id" varchar NOT NULL,
	"estado_anterior" varchar,
	"estado_nuevo" varchar NOT NULL,
	"user_id" varchar NOT NULL,
	"user_name" varchar,
	"notas" text,
	"created_at" timestamp DEFAULT now()
);
--> statement-breakpoint
CREATE TABLE "reclamos_generales_photos" (
	"id" varchar PRIMARY KEY DEFAULT gen_random_uuid() NOT NULL,
	"reclamo_id" varchar NOT NULL,
	"photo_url" text NOT NULL,
	"description" text,
	"uploaded_at" timestamp DEFAULT now()
);
--> statement-breakpoint
CREATE TABLE "sales_transactions" (
	"id" varchar PRIMARY KEY DEFAULT gen_random_uuid() NOT NULL,
	"nudo" varchar NOT NULL,
	"feemdo" date NOT NULL,
	"koprct" varchar,
	"nokoen" text,
	"noruen" varchar,
	"nokoprct" text,
	"nokofu" varchar,
	"caprad2" numeric(10, 2),
	"idmaeedo" numeric(10, 2),
	"tido" varchar,
	"endo" varchar,
	"suendo" varchar,
	"sudo" varchar,
	"feulvedo" date,
	"kofudo" varchar,
	"modo" varchar,
	"timodo" varchar,
	"tamodo" numeric(10, 2),
	"caprad" numeric(10, 2),
	"caprex" numeric(10, 2),
	"vanedo" numeric(15, 2),
	"vaivdo" numeric(15, 2),
	"vabrdo" numeric(15, 2),
	"lilg" varchar,
	"nulido" varchar,
	"sulido" varchar,
	"luvtlido" integer,
	"bosulido" varchar,
	"kofulido" varchar,
	"prct" varchar,
	"tict" varchar,
	"tipr" varchar,
	"nusepr" varchar,
	"udtrpr" numeric(10, 2),
	"rludpr" numeric(10, 2),
	"caprco1" numeric(10, 2),
	"caprad1" numeric(10, 2),
	"caprex1" numeric(10, 2),
	"caprnc1" numeric(10, 2),
	"ud01pr" varchar,
	"caprco2" numeric(10, 2),
	"caprex2" numeric(10, 2),
	"caprnc2" numeric(10, 2),
	"ud02pr" varchar,
	"ppprne" numeric(15, 2),
	"ppprbr" numeric(15, 2),
	"vaneli" numeric(15, 2),
	"vabrli" numeric(15, 2),
	"feemli" date,
	"feerli" date,
	"ppprpm" numeric(15, 2),
	"ppprpmifrs" numeric(15, 2),
	"logistica" numeric(10, 2),
	"eslido" varchar,
	"ppprnere1" numeric(15, 2),
	"ppprnere2" numeric(15, 2),
	"idmaeddo" numeric(15, 2),
	"fmpr" varchar,
	"mrpr" varchar,
	"zona" varchar,
	"ruen" varchar,
	"recaprre" numeric(15, 2),
	"pfpr" varchar,
	"hfpr" varchar,
	"monto" numeric(15, 2),
	"ocdo" varchar,
	"nofmpr" varchar,
	"nopfpr" varchar,
	"nohfpr" varchar,
	"devol1" numeric(10, 2),
	"devol2" numeric(10, 2),
	"stockfis" numeric(10, 2),
	"listacost" varchar,
	"liscosmod" numeric(10, 2),
	"nokozo" varchar,
	"nosudo" varchar,
	"nokofudo" varchar,
	"nobosuli" varchar,
	"nomrpr" varchar,
	"created_at" timestamp DEFAULT now(),
	"updated_at" timestamp DEFAULT now()
);
--> statement-breakpoint
CREATE TABLE "salespeople_users" (
	"id" varchar PRIMARY KEY DEFAULT gen_random_uuid() NOT NULL,
	"salesperson_name" varchar NOT NULL,
	"username" varchar,
	"email" varchar,
	"password" varchar,
	"is_active" boolean DEFAULT true,
	"role" varchar DEFAULT 'salesperson',
	"supervisor_id" varchar,
	"assigned_segment" varchar,
	"created_at" timestamp DEFAULT now(),
	"updated_at" timestamp DEFAULT now(),
	CONSTRAINT "salespeople_users_salesperson_name_unique" UNIQUE("salesperson_name"),
	CONSTRAINT "salespeople_users_username_unique" UNIQUE("username"),
	CONSTRAINT "salespeople_users_email_unique" UNIQUE("email")
);
--> statement-breakpoint
CREATE TABLE "sessions" (
	"sid" varchar PRIMARY KEY NOT NULL,
	"sess" jsonb NOT NULL,
	"expire" timestamp NOT NULL
);
--> statement-breakpoint
CREATE TABLE "solicitudes_marketing" (
	"id" varchar PRIMARY KEY DEFAULT gen_random_uuid() NOT NULL,
	"titulo" varchar(255) NOT NULL,
	"descripcion" text NOT NULL,
	"monto" numeric(15, 2),
	"url_referencia" text,
	"pdf_presupuesto" text,
	"pasos" jsonb DEFAULT '[]'::jsonb,
	"notas" text,
	"urgencia" varchar DEFAULT 'baja' NOT NULL,
	"estado" varchar DEFAULT 'solicitado' NOT NULL,
	"supervisor_id" varchar,
	"supervisor_name" varchar,
	"fecha_solicitud" timestamp DEFAULT now() NOT NULL,
	"fecha_entrega" date,
	"fecha_completado" timestamp,
	"motivo_rechazo" text,
	"mes" integer NOT NULL,
	"anio" integer NOT NULL,
	"created_at" timestamp DEFAULT now(),
	"updated_at" timestamp DEFAULT now()
);
--> statement-breakpoint
CREATE TABLE "ventas"."stg_maeddo" (
	"idmaeddo" numeric(20, 0) PRIMARY KEY NOT NULL,
	"idmaeedo" numeric(20, 0) NOT NULL,
	"koprct" text,
	"nokopr" text,
	"udtrpr" text,
	"caprco" numeric(18, 4),
	"preuni" numeric(18, 6),
	"vaneli" numeric(18, 4),
	"devol1" numeric(18, 4),
	"devol2" numeric(18, 4),
	"stockfis" numeric(18, 4)
);
--> statement-breakpoint
CREATE TABLE "ventas"."stg_maeedo" (
	"idmaeedo" numeric(20, 0) PRIMARY KEY NOT NULL,
	"tido" text,
	"nudo" text,
	"feemli" date,
	"endo" text,
	"suendo" text,
	"suli" text,
	"bosulido" text,
	"kofudo" text,
	"vanedo" numeric(18, 4),
	"vaivdo" numeric(18, 4),
	"vabrdo" numeric(18, 4)
);
--> statement-breakpoint
CREATE TABLE "ventas"."stg_maeen" (
	"koen" text PRIMARY KEY NOT NULL,
	"nokoen" text,
	"rut" text,
	"zona" text
);
--> statement-breakpoint
CREATE TABLE "ventas"."stg_maepr" (
	"kopr" text PRIMARY KEY NOT NULL,
	"nomrpr" text,
	"ud01pr" text,
	"ud02pr" text,
	"tipr" text
);
--> statement-breakpoint
CREATE TABLE "ventas"."stg_maeven" (
	"kofu" text PRIMARY KEY NOT NULL,
	"nokofu" text
);
--> statement-breakpoint
CREATE TABLE "ventas"."stg_tabbo" (
	"suli" text NOT NULL,
	"bosuli" text NOT NULL,
	"nobosuli" text,
	CONSTRAINT "stg_tabbo_suli_bosuli_pk" PRIMARY KEY("suli","bosuli")
);
--> statement-breakpoint
CREATE TABLE "ventas"."stg_tabpp" (
	"kopr" text PRIMARY KEY NOT NULL,
	"listacost" numeric(18, 4),
	"liscosmod" numeric(18, 4)
);
--> statement-breakpoint
CREATE TABLE "store_banners" (
	"id" varchar PRIMARY KEY DEFAULT gen_random_uuid() NOT NULL,
	"titulo" varchar NOT NULL,
	"subtitulo" varchar,
	"descripcion" text,
	"imagen_desktop" varchar NOT NULL,
	"imagen_mobile" varchar,
	"color_fondo" varchar DEFAULT '#FF6B35',
	"color_texto" varchar DEFAULT '#FFFFFF',
	"link_url" varchar,
	"orden" integer DEFAULT 0,
	"activo" boolean DEFAULT true,
	"tipo_visualizacion" varchar DEFAULT 'hero',
	"fecha_inicio" timestamp,
	"fecha_fin" timestamp,
	"created_at" timestamp DEFAULT now(),
	"updated_at" timestamp DEFAULT now()
);
--> statement-breakpoint
CREATE TABLE "store_config" (
	"id" varchar PRIMARY KEY DEFAULT gen_random_uuid() NOT NULL,
	"site_name" varchar DEFAULT 'Pinturas Panoramica',
	"logo_url" varchar,
	"favicon_url" varchar,
	"primary_color" varchar DEFAULT '#FF6B35',
	"secondary_color" varchar DEFAULT '#2C3E50',
	"header_search_placeholder" varchar DEFAULT 'Buscar productos...',
	"contact_info" jsonb,
	"social_media" jsonb,
	"seo_settings" jsonb,
	"active" boolean DEFAULT true,
	"created_at" timestamp DEFAULT now(),
	"updated_at" timestamp DEFAULT now()
);
--> statement-breakpoint
CREATE TABLE "store_navigation" (
	"id" varchar PRIMARY KEY DEFAULT gen_random_uuid() NOT NULL,
	"nombre" varchar NOT NULL,
	"slug" varchar NOT NULL,
	"icono" varchar,
	"descripcion" text,
	"parent_id" varchar,
	"orden" integer DEFAULT 0,
	"activo" boolean DEFAULT true,
	"link_externo" varchar,
	"created_at" timestamp DEFAULT now(),
	"updated_at" timestamp DEFAULT now(),
	CONSTRAINT "store_navigation_slug_unique" UNIQUE("slug")
);
--> statement-breakpoint
CREATE TABLE "task_assignments" (
	"id" varchar PRIMARY KEY DEFAULT gen_random_uuid() NOT NULL,
	"task_id" varchar NOT NULL,
	"assignee_type" varchar NOT NULL,
	"assignee_id" varchar NOT NULL,
	"status" varchar DEFAULT 'pending',
	"read_at" timestamp,
	"completed_at" timestamp,
	"notes" text,
	"evidence_images" text[],
	"created_at" timestamp DEFAULT now()
);
--> statement-breakpoint
CREATE TABLE "tasks" (
	"id" varchar PRIMARY KEY DEFAULT gen_random_uuid() NOT NULL,
	"title" text NOT NULL,
	"description" text,
	"type" varchar NOT NULL,
	"status" varchar DEFAULT 'pendiente',
	"progress" integer DEFAULT 0,
	"priority" varchar DEFAULT 'medium',
	"due_date" timestamp,
	"created_by_user_id" varchar NOT NULL,
	"assigned_to_user_id" varchar,
	"payload" jsonb,
	"created_at" timestamp DEFAULT now(),
	"updated_at" timestamp DEFAULT now()
);
--> statement-breakpoint
CREATE TABLE "users" (
	"id" varchar PRIMARY KEY DEFAULT gen_random_uuid() NOT NULL,
	"email" varchar NOT NULL,
	"password" varchar,
	"first_name" varchar,
	"last_name" varchar,
	"profile_image_url" varchar,
	"role" varchar DEFAULT 'user',
	"created_at" timestamp DEFAULT now(),
	"updated_at" timestamp DEFAULT now(),
	CONSTRAINT "users_email_unique" UNIQUE("email")
);
--> statement-breakpoint
CREATE TABLE "visitas_tecnicas" (
	"id" varchar PRIMARY KEY DEFAULT gen_random_uuid() NOT NULL,
	"obra_id" varchar,
	"nombre_obra" text NOT NULL,
	"direccion_obra" text NOT NULL,
	"tecnico_id" varchar NOT NULL,
	"vendedor_id" varchar,
	"cliente_id" varchar,
	"cliente_manual" text,
	"recepcionista_nombre" text,
	"recepcionista_cargo" text,
	"estado" varchar DEFAULT 'borrador' NOT NULL,
	"aplicacion_general" varchar,
	"tipo_superficie" text,
	"ambiente" varchar,
	"condiciones_climaticas" text,
	"dilucion" text,
	"observaciones_generales" text,
	"comentarios" text,
	"created_at" timestamp DEFAULT now(),
	"updated_at" timestamp DEFAULT now()
);
--> statement-breakpoint
CREATE TABLE "warehouses" (
	"id" varchar PRIMARY KEY DEFAULT gen_random_uuid() NOT NULL,
	"kobo" varchar NOT NULL,
	"kosu" varchar NOT NULL,
	"name" varchar NOT NULL,
	"branch_name" varchar,
	"location" text,
	"active" boolean DEFAULT true,
	"created_at" timestamp DEFAULT now(),
	"updated_at" timestamp DEFAULT now(),
	CONSTRAINT "warehouses_kobo_unique" UNIQUE("kobo"),
	CONSTRAINT "unique_warehouse_branch" UNIQUE("kobo","kosu")
);
--> statement-breakpoint
ALTER TABLE "colores" ADD CONSTRAINT "colores_base_id_bases_base_id_fk" FOREIGN KEY ("base_id") REFERENCES "public"."bases"("base_id") ON DELETE no action ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "recetas" ADD CONSTRAINT "recetas_color_id_colores_color_id_fk" FOREIGN KEY ("color_id") REFERENCES "public"."colores"("color_id") ON DELETE no action ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "recetas" ADD CONSTRAINT "recetas_pigmento_code_pigments_pigmento_code_fk" FOREIGN KEY ("pigmento_code") REFERENCES "public"."pigments"("pigmento_code") ON DELETE no action ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "solicitudes_marketing" ADD CONSTRAINT "solicitudes_marketing_supervisor_id_salespeople_users_id_fk" FOREIGN KEY ("supervisor_id") REFERENCES "public"."salespeople_users"("id") ON DELETE no action ON UPDATE no action;--> statement-breakpoint
CREATE INDEX "IDX_clients_koen" ON "clients" USING btree ("koen");--> statement-breakpoint
CREATE INDEX "IDX_clients_nokoen" ON "clients" USING btree ("nokoen");--> statement-breakpoint
CREATE INDEX "IDX_comuna_normalized" ON "comuna_region_mapping" USING btree ("comuna_normalized");--> statement-breakpoint
CREATE INDEX "IDX_region" ON "comuna_region_mapping" USING btree ("region");--> statement-breakpoint
CREATE INDEX "IDX_ecommerce_orders_client_id" ON "ecommerce_orders" USING btree ("client_id");--> statement-breakpoint
CREATE INDEX "IDX_ecommerce_orders_salesperson_id" ON "ecommerce_orders" USING btree ("assigned_salesperson_id");--> statement-breakpoint
CREATE INDEX "IDX_ecommerce_orders_status" ON "ecommerce_orders" USING btree ("status");--> statement-breakpoint
CREATE INDEX "ix_fact_ventas_feemli_id" ON "ventas"."fact_ventas" USING btree ("feemli","idmaeedo","idmaeddo");--> statement-breakpoint
CREATE INDEX "ix_fact_ventas_cliente" ON "ventas"."fact_ventas" USING btree ("endo");--> statement-breakpoint
CREATE INDEX "ix_fact_ventas_producto" ON "ventas"."fact_ventas" USING btree ("koprct");--> statement-breakpoint
CREATE INDEX "ix_fact_ventas_vendedor" ON "ventas"."fact_ventas" USING btree ("kofudo");--> statement-breakpoint
CREATE INDEX "ix_fact_ventas_bodega" ON "ventas"."fact_ventas" USING btree ("bosulido");--> statement-breakpoint
CREATE INDEX "IDX_notifications_user_id" ON "notifications" USING btree ("user_id");--> statement-breakpoint
CREATE INDEX "IDX_notifications_type" ON "notifications" USING btree ("type");--> statement-breakpoint
CREATE INDEX "IDX_notifications_read" ON "notifications" USING btree ("read");--> statement-breakpoint
CREATE INDEX "nvv_pending_sales_nudo_idx" ON "nvv_pending_sales" USING btree ("NUDO");--> statement-breakpoint
CREATE INDEX "nvv_pending_sales_nokoen_idx" ON "nvv_pending_sales" USING btree ("NOKOEN");--> statement-breakpoint
CREATE INDEX "nvv_pending_sales_koprct_idx" ON "nvv_pending_sales" USING btree ("KOPRCT");--> statement-breakpoint
CREATE INDEX "nvv_pending_sales_feerli_idx" ON "nvv_pending_sales" USING btree ("FEERLI");--> statement-breakpoint
CREATE INDEX "nvv_pending_sales_kofulido_idx" ON "nvv_pending_sales" USING btree ("KOFULIDO");--> statement-breakpoint
CREATE INDEX "nvv_pending_sales_import_batch_idx" ON "nvv_pending_sales" USING btree ("import_batch");--> statement-breakpoint
CREATE UNIQUE INDEX "unique_mes_anio" ON "presupuesto_marketing" USING btree ("mes","anio");--> statement-breakpoint
CREATE INDEX "product_image_idx" ON "product_images" USING btree ("ecommerce_product_id","orden");--> statement-breakpoint
CREATE UNIQUE INDEX "products_slug_unique" ON "products" USING btree ("slug") WHERE "products"."slug" is not null;--> statement-breakpoint
CREATE INDEX "IDX_promesas_compra_vendedor" ON "promesas_compra" USING btree ("vendedor_id");--> statement-breakpoint
CREATE INDEX "IDX_promesas_compra_semana" ON "promesas_compra" USING btree ("semana");--> statement-breakpoint
CREATE INDEX "IDX_promesas_compra_cliente" ON "promesas_compra" USING btree ("cliente_id");--> statement-breakpoint
CREATE INDEX "IDX_reclamos_gen_vendedor_id" ON "reclamos_generales" USING btree ("vendedor_id");--> statement-breakpoint
CREATE INDEX "IDX_reclamos_gen_tecnico_id" ON "reclamos_generales" USING btree ("tecnico_id");--> statement-breakpoint
CREATE INDEX "IDX_reclamos_gen_estado" ON "reclamos_generales" USING btree ("estado");--> statement-breakpoint
CREATE INDEX "IDX_reclamos_gen_gravedad" ON "reclamos_generales" USING btree ("gravedad");--> statement-breakpoint
CREATE INDEX "IDX_reclamos_gen_hist_reclamo_id" ON "reclamos_generales_historial" USING btree ("reclamo_id");--> statement-breakpoint
CREATE INDEX "IDX_reclamos_gen_photos_reclamo_id" ON "reclamos_generales_photos" USING btree ("reclamo_id");--> statement-breakpoint
CREATE INDEX "IDX_session_expire" ON "sessions" USING btree ("expire");--> statement-breakpoint
CREATE INDEX "IDX_tasks_assigned_to_user_id" ON "tasks" USING btree ("assigned_to_user_id");--> statement-breakpoint
CREATE INDEX "IDX_tasks_status" ON "tasks" USING btree ("status");--> statement-breakpoint
CREATE INDEX "IDX_tasks_type" ON "tasks" USING btree ("type");--> statement-breakpoint
CREATE INDEX "IDX_tasks_due_date" ON "tasks" USING btree ("due_date");