-- 091: Solicitudes a laboratorio de tintometría (sep-2026).
--
-- Un vendedor le pide a laboratorio la fórmula y/o el precio de un color para
-- un cliente, con los datos de la planilla "Solicitud de fórmula tintométrica"
-- que antes circulaba por correo. Laboratorio responde en el panel: la fórmula
-- queda en la carta (tinto_formulas, origen 'laboratorio') y el precio en la
-- solicitud. Mensajes y cambios de estado van a tinto_solicitud_mensajes.
--
-- Lo mismo lo crea ensureTintometriaTablas (server/migrations.ts) al arrancar.

CREATE TABLE IF NOT EXISTS tinto_solicitudes (
  id VARCHAR PRIMARY KEY DEFAULT gen_random_uuid(),
  numero INTEGER GENERATED BY DEFAULT AS IDENTITY,
  tipo VARCHAR(20) NOT NULL,
  estado VARCHAR(20) NOT NULL DEFAULT 'enviada',
  cliente_id VARCHAR,
  cliente_nombre TEXT NOT NULL,
  ciudad VARCHAR(120),
  obra TEXT,
  color_id VARCHAR,
  color_codigo VARCHAR(60) NOT NULL,
  color_nombre TEXT,
  cartilla VARCHAR(60),
  linea TEXT NOT NULL,
  base TEXT,
  formato TEXT,
  cantidad TEXT,
  patron TEXT,
  lote TEXT,
  observaciones TEXT,
  adjuntos JSONB NOT NULL DEFAULT '[]'::jsonb,
  formula_id VARCHAR,
  precio NUMERIC(15,2),
  precio_unidad TEXT,
  respuesta TEXT,
  respondida_por_id VARCHAR,
  respondida_por_nombre TEXT,
  respondida_at TIMESTAMPTZ,
  solicitante_id VARCHAR,
  solicitante_nombre TEXT,
  supervisor_id VARCHAR,
  vista_solicitante_at TIMESTAMPTZ,
  vista_laboratorio_at TIMESTAMPTZ,
  ultimo_movimiento_at TIMESTAMPTZ DEFAULT now(),
  ultimo_movimiento_de VARCHAR(20),
  created_at TIMESTAMPTZ DEFAULT now(),
  updated_at TIMESTAMPTZ DEFAULT now()
);
CREATE INDEX IF NOT EXISTS "IDX_tinto_solicitudes_solicitante" ON tinto_solicitudes (solicitante_id);
CREATE INDEX IF NOT EXISTS "IDX_tinto_solicitudes_estado" ON tinto_solicitudes (estado);

CREATE TABLE IF NOT EXISTS tinto_solicitud_mensajes (
  id VARCHAR PRIMARY KEY DEFAULT gen_random_uuid(),
  solicitud_id VARCHAR NOT NULL REFERENCES tinto_solicitudes(id) ON DELETE CASCADE,
  autor_id VARCHAR,
  autor_nombre TEXT,
  lado VARCHAR(20) NOT NULL,
  texto TEXT,
  adjunto_url TEXT,
  adjunto_nombre TEXT,
  evento VARCHAR(30),
  created_at TIMESTAMPTZ DEFAULT now()
);
CREATE INDEX IF NOT EXISTS "IDX_tinto_solicitud_mensajes_solicitud" ON tinto_solicitud_mensajes (solicitud_id);

-- Destinatarios del aviso, editables desde Configuración → Correos. Se siembra
-- vacío: mientras no se definan, el aviso le llega a los usuarios con el rol
-- Laboratorio.
INSERT INTO email_notification_settings (notification_type, enabled, recipients, cc_recipients, display_name, description)
VALUES (
  'solicitud_laboratorio',
  true,
  '',
  '',
  'Solicitud a laboratorio (tintometría)',
  'A quién le llega una solicitud de fórmula o precio nueva, además de los usuarios con el rol Laboratorio. Quien la pide va siempre en copia.'
)
ON CONFLICT (notification_type) DO NOTHING;
