// Mapeo de comunas a regiones de Chile
export const COMUNA_TO_REGION: Record<string, string> = {
  // Región de Arica y Parinacota
  'ARICA': 'Arica y Parinacota',
  'CAMARONES': 'Arica y Parinacota',
  'GENERAL LAGOS': 'Arica y Parinacota',
  'PUTRE': 'Arica y Parinacota',
  
  // Región de Tarapacá
  'IQUIQUE': 'Tarapacá',
  'ALTO HOSPICIO': 'Tarapacá',
  'CAMIÑA': 'Tarapacá',
  'COLCHANE': 'Tarapacá',
  'HUARA': 'Tarapacá',
  'PICA': 'Tarapacá',
  'POZO ALMONTE': 'Tarapacá',
  
  // Región de Antofagasta
  'ANTOFAGASTA': 'Antofagasta',
  'CALAMA': 'Antofagasta',
  'MEJILLONES': 'Antofagasta',
  'OLLAGUE': 'Antofagasta',
  'SAN PEDRO DE ATACAMA': 'Antofagasta',
  'SIERRA GORDA': 'Antofagasta',
  'TALTAL': 'Antofagasta',
  'TOCOPILLA': 'Antofagasta',
  'MARIA ELENA': 'Antofagasta',
  
  // Región de Atacama
  'COPIAPO': 'Atacama',
  'CALDERA': 'Atacama',
  'TIERRA AMARILLA': 'Atacama',
  'CHAÑARAL': 'Atacama',
  'DIEGO DE ALMAGRO': 'Atacama',
  'VALLENAR': 'Atacama',
  'FREIRINA': 'Atacama',
  'HUASCO': 'Atacama',
  'ALTO DEL CARMEN': 'Atacama',
  
  // Región de Coquimbo
  'LA SERENA': 'Coquimbo',
  'COQUIMBO': 'Coquimbo',
  'ANDACOLLO': 'Coquimbo',
  'LA HIGUERA': 'Coquimbo',
  'PAIGUANO': 'Coquimbo',
  'VICUÑA': 'Coquimbo',
  'ILLAPEL': 'Coquimbo',
  'CANELA': 'Coquimbo',
  'LOS VILOS': 'Coquimbo',
  'SALAMANCA': 'Coquimbo',
  'OVALLE': 'Coquimbo',
  'COMBARBALA': 'Coquimbo',
  'MONTE PATRIA': 'Coquimbo',
  'PUNITAQUI': 'Coquimbo',
  'RIO HURTADO': 'Coquimbo',
  
  // Región de Valparaíso
  'VALPARAISO': 'Valparaíso',
  'VIÑA DEL MAR': 'Valparaíso',
  'CASABLANCA': 'Valparaíso',
  'CONCON': 'Valparaíso',
  'JUAN FERNANDEZ': 'Valparaíso',
  'PUCHUNCAVI': 'Valparaíso',
  'QUINTERO': 'Valparaíso',
  'VILLA ALEMANA': 'Valparaíso',
  'QUILPUE': 'Valparaíso',
  'LIMACHE': 'Valparaíso',
  'OLMUE': 'Valparaíso',
  'QUILLOTA': 'Valparaíso',
  'LA CALERA': 'Valparaíso',
  'HIJUELAS': 'Valparaíso',
  'LA CRUZ': 'Valparaíso',
  'NOGALES': 'Valparaíso',
  'SAN ANTONIO': 'Valparaíso',
  'ALGARROBO': 'Valparaíso',
  'CARTAGENA': 'Valparaíso',
  'EL QUISCO': 'Valparaíso',
  'EL TABO': 'Valparaíso',
  'SANTO DOMINGO': 'Valparaíso',
  'SAN FELIPE': 'Valparaíso',
  'CATEMU': 'Valparaíso',
  'LLAILLAY': 'Valparaíso',
  'PANQUEHUE': 'Valparaíso',
  'PUTAENDO': 'Valparaíso',
  'SANTA MARIA': 'Valparaíso',
  'LOS ANDES': 'Valparaíso',
  'CALLE LARGA': 'Valparaíso',
  'RINCONADA': 'Valparaíso',
  'SAN ESTEBAN': 'Valparaíso',
  'ISLA DE PASCUA': 'Valparaíso',
  'PETORCA': 'Valparaíso',
  'CABILDO': 'Valparaíso',
  'PAPUDO': 'Valparaíso',
  'ZAPALLAR': 'Valparaíso',
  
  // Región Metropolitana
  'SANTIAGO': 'Metropolitana',
  'CERRILLOS': 'Metropolitana',
  'CERRO NAVIA': 'Metropolitana',
  'CONCHALI': 'Metropolitana',
  'EL BOSQUE': 'Metropolitana',
  'ESTACION CENTRAL': 'Metropolitana',
  'HUECHURABA': 'Metropolitana',
  'INDEPENDENCIA': 'Metropolitana',
  'LA CISTERNA': 'Metropolitana',
  'LA GRANJA': 'Metropolitana',
  'LA PINTANA': 'Metropolitana',
  'LA REINA': 'Metropolitana',
  'LAS CONDES': 'Metropolitana',
  'LO BARNECHEA': 'Metropolitana',
  'LO ESPEJO': 'Metropolitana',
  'LO PRADO': 'Metropolitana',
  'MACUL': 'Metropolitana',
  'MAIPU': 'Metropolitana',
  'ÑUÑOA': 'Metropolitana',
  'PEDRO AGUIRRE CERDA': 'Metropolitana',
  'PEÑALOLEN': 'Metropolitana',
  'PROVIDENCIA': 'Metropolitana',
  'PUDAHUEL': 'Metropolitana',
  'QUILICURA': 'Metropolitana',
  'QUINTA NORMAL': 'Metropolitana',
  'RECOLETA': 'Metropolitana',
  'RENCA': 'Metropolitana',
  'SAN JOAQUIN': 'Metropolitana',
  'SAN MIGUEL': 'Metropolitana',
  'SAN RAMON': 'Metropolitana',
  'VITACURA': 'Metropolitana',
  'PUENTE ALTO': 'Metropolitana',
  'PIRQUE': 'Metropolitana',
  'SAN JOSE DE MAIPO': 'Metropolitana',
  'COLINA': 'Metropolitana',
  'LAMPA': 'Metropolitana',
  'TILTIL': 'Metropolitana',
  'SAN BERNARDO': 'Metropolitana',
  'BUIN': 'Metropolitana',
  'CALERA DE TANGO': 'Metropolitana',
  'PAINE': 'Metropolitana',
  'MELIPILLA': 'Metropolitana',
  'ALHUE': 'Metropolitana',
  'CURACAVI': 'Metropolitana',
  'MARIA PINTO': 'Metropolitana',
  'SAN PEDRO': 'Metropolitana',
  'TALAGANTE': 'Metropolitana',
  'EL MONTE': 'Metropolitana',
  'ISLA DE MAIPO': 'Metropolitana',
  'PADRE HURTADO': 'Metropolitana',
  'PEÑA FLOR': 'Metropolitana',
  
  // Región del Libertador Bernardo O'Higgins
  'RANCAGUA': 'O\'Higgins',
  'CODEGUA': 'O\'Higgins',
  'COINCO': 'O\'Higgins',
  'COLTAUCO': 'O\'Higgins',
  'DOÑIHUE': 'O\'Higgins',
  'GRANEROS': 'O\'Higgins',
  'LAS CABRAS': 'O\'Higgins',
  'MACHALI': 'O\'Higgins',
  'MALLOA': 'O\'Higgins',
  'MOSTAZAL': 'O\'Higgins',
  'OLIVAR': 'O\'Higgins',
  'PEUMO': 'O\'Higgins',
  'PICHIDEGUA': 'O\'Higgins',
  'QUINTA DE TILCOCO': 'O\'Higgins',
  'RENGO': 'O\'Higgins',
  'REQUINOA': 'O\'Higgins',
  'SAN VICENTE': 'O\'Higgins',
  'PICHILEMU': 'O\'Higgins',
  'LA ESTRELLA': 'O\'Higgins',
  'LITUECHE': 'O\'Higgins',
  'MARCHIGUE': 'O\'Higgins',
  'NAVIDAD': 'O\'Higgins',
  'PAREDONES': 'O\'Higgins',
  'SAN FERNANDO': 'O\'Higgins',
  'CHEPICA': 'O\'Higgins',
  'CHIMBARONGO': 'O\'Higgins',
  'LOLOL': 'O\'Higgins',
  'NANCAGUA': 'O\'Higgins',
  'PALMILLA': 'O\'Higgins',
  'PERALILLO': 'O\'Higgins',
  'PLACILLA': 'O\'Higgins',
  'PUMANQUE': 'O\'Higgins',
  'SANTA CRUZ': 'O\'Higgins',
  
  // Región del Maule
  'TALCA': 'Maule',
  'CONSTITUCION': 'Maule',
  'CUREPTO': 'Maule',
  'EMPEDRADO': 'Maule',
  'MAULE': 'Maule',
  'PELARCO': 'Maule',
  'PENCAHUE': 'Maule',
  'RIO CLARO': 'Maule',
  'SAN CLEMENTE': 'Maule',
  'SAN RAFAEL': 'Maule',
  'CURICO': 'Maule',
  'HUALAÑE': 'Maule',
  'LICANTEN': 'Maule',
  'MOLINA': 'Maule',
  'RAUCO': 'Maule',
  'ROMERAL': 'Maule',
  'SAGRADA FAMILIA': 'Maule',
  'TENO': 'Maule',
  'VICHUQUEN': 'Maule',
  'LINARES': 'Maule',
  'COLBUN': 'Maule',
  'LONGAVI': 'Maule',
  'PARRAL': 'Maule',
  'RETIRO': 'Maule',
  'SAN JAVIER': 'Maule',
  'VILLA ALEGRE': 'Maule',
  'YERBAS BUENAS': 'Maule',
  'CAUQUENES': 'Maule',
  'CHANCO': 'Maule',
  'PELLUHUE': 'Maule',
  
  // Región de Ñuble
  'CHILLAN': 'Ñuble',
  'BULNES': 'Ñuble',
  'CHILLAN VIEJO': 'Ñuble',
  'EL CARMEN': 'Ñuble',
  'PEMUCO': 'Ñuble',
  'PINTO': 'Ñuble',
  'QUILLON': 'Ñuble',
  'SAN IGNACIO': 'Ñuble',
  'YUNGAY': 'Ñuble',
  'COBQUECURA': 'Ñuble',
  'COELEMU': 'Ñuble',
  'NINHUE': 'Ñuble',
  'PORTEZUELO': 'Ñuble',
  'QUIRIHUE': 'Ñuble',
  'RANQUIL': 'Ñuble',
  'TREHUACO': 'Ñuble',
  'SAN CARLOS': 'Ñuble',
  'COIHUECO': 'Ñuble',
  'ÑIQUEN': 'Ñuble',
  'SAN FABIAN': 'Ñuble',
  'SAN NICOLAS': 'Ñuble',
  
  // Región del Biobío
  'CONCEPCION': 'Biobío',
  'CORONEL': 'Biobío',
  'CHIGUAYANTE': 'Biobío',
  'FLORIDA': 'Biobío',
  'HUALQUI': 'Biobío',
  'LOTA': 'Biobío',
  'PENCO': 'Biobío',
  'SAN PEDRO DE LA PAZ': 'Biobío',
  'SANTA JUANA': 'Biobío',
  'TALCAHUANO': 'Biobío',
  'TOME': 'Biobío',
  'HUALPEN': 'Biobío',
  'LEBU': 'Biobío',
  'ARAUCO': 'Biobío',
  'CAÑETE': 'Biobío',
  'CONTULMO': 'Biobío',
  'CURANILAHUE': 'Biobío',
  'LOS ALAMOS': 'Biobío',
  'TIRUA': 'Biobío',
  'LOS ANGELES': 'Biobío',
  'ANTUCO': 'Biobío',
  'CABRERO': 'Biobío',
  'LAJA': 'Biobío',
  'MULCHEN': 'Biobío',
  'NACIMIENTO': 'Biobío',
  'NEGRETE': 'Biobío',
  'QUILACO': 'Biobío',
  'QUILLECO': 'Biobío',
  'SAN ROSENDO': 'Biobío',
  'SANTA BARBARA': 'Biobío',
  'TUCAPEL': 'Biobío',
  'YUMBEL': 'Biobío',
  'ALTO BIOBIO': 'Biobío',
  
  // Región de La Araucanía
  'TEMUCO': 'Araucanía',
  'CARAHUE': 'Araucanía',
  'CUNCO': 'Araucanía',
  'CURARREHUE': 'Araucanía',
  'FREIRE': 'Araucanía',
  'GALVARINO': 'Araucanía',
  'GORBEA': 'Araucanía',
  'LAUTARO': 'Araucanía',
  'LONCOCHE': 'Araucanía',
  'MELIPEUCO': 'Araucanía',
  'NUEVA IMPERIAL': 'Araucanía',
  'PADRE LAS CASAS': 'Araucanía',
  'PERQUENCO': 'Araucanía',
  'PITRUFQUEN': 'Araucanía',
  'PUCON': 'Araucanía',
  'SAAVEDRA': 'Araucanía',
  'TEODORO SCHMIDT': 'Araucanía',
  'TOLTEN': 'Araucanía',
  'VILCUN': 'Araucanía',
  'VILLARRICA': 'Araucanía',
  'ANGOL': 'Araucanía',
  'COLLIPULLI': 'Araucanía',
  'CURACAUTIN': 'Araucanía',
  'ERCILLA': 'Araucanía',
  'LONQUIMAY': 'Araucanía',
  'LOS SAUCES': 'Araucanía',
  'LUMACO': 'Araucanía',
  'PUREN': 'Araucanía',
  'RENAICO': 'Araucanía',
  'TRAIGUEN': 'Araucanía',
  'VICTORIA': 'Araucanía',
  
  // Región de Los Ríos
  'VALDIVIA': 'Los Ríos',
  'CORRAL': 'Los Ríos',
  'LANCO': 'Los Ríos',
  'LOS LAGOS': 'Los Ríos',
  'MAFIL': 'Los Ríos',
  'MARIQUINA': 'Los Ríos',
  'PAILLACO': 'Los Ríos',
  'PANGUIPULLI': 'Los Ríos',
  'LA UNION': 'Los Ríos',
  'FUTRONO': 'Los Ríos',
  'LAGO RANCO': 'Los Ríos',
  'RIO BUENO': 'Los Ríos',
  
  // Región de Los Lagos
  'PUERTO MONTT': 'Los Lagos',
  'CALBUCO': 'Los Lagos',
  'COCHAMO': 'Los Lagos',
  'FRESIA': 'Los Lagos',
  'FRUTILLAR': 'Los Lagos',
  'LOS MUERMOS': 'Los Lagos',
  'LLANQUIHUE': 'Los Lagos',
  'MAULLIN': 'Los Lagos',
  'PUERTO VARAS': 'Los Lagos',
  'CASTRO': 'Los Lagos',
  'ANCUD': 'Los Lagos',
  'CHONCHI': 'Los Lagos',
  'CURACO DE VELEZ': 'Los Lagos',
  'DALCAHUE': 'Los Lagos',
  'PUQUELDON': 'Los Lagos',
  'QUEILEN': 'Los Lagos',
  'QUELLON': 'Los Lagos',
  'QUINCHAO': 'Los Lagos',
  'OSORNO': 'Los Lagos',
  'PUERTO OCTAY': 'Los Lagos',
  'PURRANQUE': 'Los Lagos',
  'PUYEHUE': 'Los Lagos',
  'RIO NEGRO': 'Los Lagos',
  'SAN JUAN DE LA COSTA': 'Los Lagos',
  'SAN PABLO': 'Los Lagos',
  'CHAITEN': 'Los Lagos',
  'FUTALEUFU': 'Los Lagos',
  'HUALAIHUE': 'Los Lagos',
  'PALENA': 'Los Lagos',
  
  // Región de Aysén
  'COIHAIQUE': 'Aysén',
  'LAGO VERDE': 'Aysén',
  'AYSEN': 'Aysén',
  'CISNES': 'Aysén',
  'GUAITECAS': 'Aysén',
  'COCHRANE': 'Aysén',
  'OHIGGINS': 'Aysén',
  'TORTEL': 'Aysén',
  'CHILE CHICO': 'Aysén',
  'RIO IBAÑEZ': 'Aysén',
  
  // Región de Magallanes y Antártica Chilena
  'PUNTA ARENAS': 'Magallanes',
  'LAGUNA BLANCA': 'Magallanes',
  'RIO VERDE': 'Magallanes',
  'SAN GREGORIO': 'Magallanes',
  'CABO DE HORNOS': 'Magallanes',
  'ANTARTICA': 'Magallanes',
  'PORVENIR': 'Magallanes',
  'PRIMAVERA': 'Magallanes',
  'TIMAUKEL': 'Magallanes',
  'NATALES': 'Magallanes',
  'TORRES DEL PAINE': 'Magallanes',
};

export function getComunaRegion(comuna: string): string {
  return COMUNA_TO_REGION[comuna.toUpperCase()] || 'Región Desconocida';
}